name: Publish to PyPI
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Install main dependencies
        run: |
          python -m hatch -v -e tests

      - name: Lint
        run: |
          python -m hatch -e tests run pre-commit run --all-files

      - name: Perform unit tests
        run: |
          python -m hatch -e tests run pytest

      - name: Build & Publish
        run: |
          python -m hatch build
          python -m hatch publish
